<a href="https://colab.research.google.com/github/Morrisbang/machineLearning/blob/main/XOR_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow==1.14

In [ ]:
import tensorflow as tf

##XOR (with Binary Classification)

In [6]:
x_data = [[1,1], [2,2], [3,3]]
y_data = [[10], [20], [30]]
X = tf.placeholder(dtype = tf.float32, shape=[None, 2])
Y = tf.placeholder(dtype = tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([2, 1]))
b = tf.Variable(tf.random_normal([1]))

model = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(model - Y))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [ ]:
with tf.Session() as sess :
  sess.run(tf.global_variables_initializer())
  # Training 
  for step in range(2001):
    c, W_, b_, _ = sess.run([cost, W, b, train], feed_dict={X:x_data, Y:y_data})
    print(step, c, W_, b_)
  #Testing
  print(sess.run(model, feed_dict={X:[[4,4]]}))

In [8]:
x_data = [[0,0], [0,1], [1,0], [1,1]]
y_data = [[0], [1], [1], [0]]

X = tf.placeholder(tf.float32, shape = [None, 2] )
Y = tf.placeholder(tf.float32, shape = [None, 1] )
W = tf.Variable(tf.random_normal([2,1]))
b = tf.Variable(tf.random_normal([1]))

model = tf.sigmoid(tf.matmul(X, W)+b)
cost = tf.reduce_mean((-1)*Y*tf.log(model) + (-1)*(1-Y)*tf.log(1-model))
train = tf.train.GradientDescentOptimizer(0.1).minimize(cost)

In [9]:
prediction = tf.cast(model > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype = tf.float32))

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  #Training
  for step in range(20001):
    c, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
    if step % 2000 ==0:
      print(step, c)
  #Testing
  m, p, a = sess.run([model, prediction, accuracy], feed_dict = {X: x_data, Y: y_data})
  print(m, p, a) 

0 0.73318195
2000 0.6931472
4000 0.6931472
6000 0.6931472
8000 0.6931472
10000 0.6931472
12000 0.6931472
14000 0.6931472
16000 0.6931472
18000 0.6931472
20000 0.6931472
[[0.5]
 [0.5]
 [0.5]
 [0.5]] [[0.]
 [0.]
 [0.]
 [0.]] 0.5


##Basic ANN 

In [19]:
x_data = [[0,0], [0,1], [1,0], [1,1]]
y_data = [[0], [1], [1], [0]]

X = tf.placeholder(tf.float32, shape = [None, 2] )
Y = tf.placeholder(tf.float32, shape = [None, 1] )
W_h = tf.Variable(tf.random_normal([2,3]))
b_h = tf.Variable(tf.random_normal([3]))
H1 = tf.sigmoid(tf.matmul(X,W_h)+b_h)

W_o = tf.Variable(tf.random_normal([3,1]))
b_o = tf.Variable(tf.random_normal([1]))
#H2 = tf.sigmoid(tf.matmul(H1,W_o)+b_o)

model = tf.sigmoid(tf.matmul(H1, W_o)+b_o)
cost = tf.reduce_mean((-1)*Y*tf.log(model) + (-1)*(1-Y)*tf.log(1-model))
train = tf.train.GradientDescentOptimizer(0.1).minimize(cost)

In [5]:
prediction = tf.cast(model > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype = tf.float32))

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  #Training
  for step in range(20001):
    c, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
    if step % 2000 ==0:
      print(step, c)
  #Testing
  m, p, a = sess.run([model, prediction, accuracy], feed_dict = {X: x_data, Y: y_data})
  print(m, p, a) 

0 1.2786146
2000 0.34051797
4000 0.05102875
6000 0.02440926
8000 0.01581477
10000 0.011642625
12000 0.009193049
14000 0.007586383
16000 0.0064533586
18000 0.005612212
20000 0.0049635326
[[0.00781787]
 [0.9951626 ]
 [0.99449486]
 [0.00163356]] [[0.]
 [1.]
 [1.]
 [0.]] 1.0


##Wide with ANN 

In [22]:
x_data = [[0,0], [0,1], [1,0], [1,1]]
y_data = [[0], [1], [1], [0]]

X = tf.placeholder(tf.float32, shape = [None, 2] )
Y = tf.placeholder(tf.float32, shape = [None, 1] )
W_h = tf.Variable(tf.random_normal([2,10]))
b_h = tf.Variable(tf.random_normal([10]))
H1 = tf.sigmoid(tf.matmul(X,W_h)+b_h)

W_o = tf.Variable(tf.random_normal([10,1]))
b_o = tf.Variable(tf.random_normal([1]))

model = tf.sigmoid(tf.matmul(H1, W_o)+b_o)
cost = tf.reduce_mean((-1)*Y*tf.log(model) + (-1)*(1-Y)*tf.log(1-model))
train = tf.train.GradientDescentOptimizer(0.1).minimize(cost)

In [23]:
prediction = tf.cast(model > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype = tf.float32))

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  #Training
  for step in range(20001):
    c, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
    if step % 2000 ==0:
      print(step, c)
  #Testing
  m, p, a = sess.run([model, prediction, accuracy], feed_dict = {X: x_data, Y: y_data})
  print(m, p, a) 

0 0.69033307
2000 0.2418887
4000 0.044848166
6000 0.01917346
8000 0.01143816
10000 0.007942054
12000 0.0060020983
14000 0.0047856197
16000 0.0039585964
18000 0.0033631725
20000 0.0029157791
[[0.00209894]
 [0.9973918 ]
 [0.9964688 ]
 [0.00340632]] [[0.]
 [1.]
 [1.]
 [0.]] 1.0


##Deep with ANN

In [14]:
x_data = [[0,0], [0,1], [1,0], [1,1]]
y_data = [[0], [1], [1], [0]]

X = tf.placeholder(tf.float32, shape = [None, 2] )
Y = tf.placeholder(tf.float32, shape = [None, 1] )
W1 = tf.Variable(tf.random_normal([2,10]))
b1 = tf.Variable(tf.random_normal([10]))
H1 = tf.sigmoid(tf.matmul(X,W1)+b1)

W2 = tf.Variable(tf.random_normal([10,5]))
b2 = tf.Variable(tf.random_normal([5]))
H2 = tf.sigmoid(tf.matmul(H1,W2)+b2)

W3 = tf.Variable(tf.random_normal([5,8]))
b3 = tf.Variable(tf.random_normal([8]))
H3 = tf.sigmoid(tf.matmul(H2,W3)+b3)

W4 = tf.Variable(tf.random_normal([8,1]))
b4 = tf.Variable(tf.random_normal([1]))

model = tf.sigmoid(tf.matmul(H3,W4)+b4)
cost = tf.reduce_mean((-1)*Y*tf.log(model) + (-1)*(1-Y)*tf.log(1-model))
train = tf.train.GradientDescentOptimizer(0.1).minimize(cost)

In [15]:
prediction = tf.cast(model > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), dtype = tf.float32))

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  #Training
  for step in range(20001):
    c, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
    if step % 2000 ==0:
      print(step, c)
  #Testing
  m, p, a = sess.run([model, prediction, accuracy], feed_dict = {X: x_data, Y: y_data})
  print(m, p, a) 

0 1.3610933
2000 0.48198557
4000 0.014179385
6000 0.0056584966
8000 0.0034192605
10000 0.0024159069
12000 0.0018531121
14000 0.001495146
16000 0.0012484551
18000 0.0010685704
20000 0.0009319305
[[9.3774963e-04]
 [9.9935013e-01]
 [9.9873012e-01]
 [8.6813484e-04]] [[0.]
 [1.]
 [1.]
 [0.]] 1.0


In [ ]:
x_data = [[0,0], [0,1], [1,0], [1,1]]
y_data = [[0], [1], [1], [0]]

X = tf.placeholder(tf.float32, shape = [None, 2] )
Y = tf.placeholder(tf.float32, shape = [None, 1] )
W1 = tf.Variable(tf.random_normal([2,10]))
b1 = tf.Variable(tf.random_normal([10]))
H1 = tf.sigmoid(tf.matmul(X,W1)+b1)

W2 = tf.Variable(tf.random_normal([10,5]))
b2 = tf.Variable(tf.random_normal([5]))
H2 = tf.sigmoid(tf.matmul(H1,W2)+b2)

W3 = tf.Variable(tf.random_normal([5,8]))
b3 = tf.Variable(tf.random_normal([8]))
H3 = tf.sigmoid(tf.matmul(H2,W3)+b3)

W4 = tf.Variable(tf.random_normal([8,1]))
b4 = tf.Variable(tf.random_normal([1]))

model = tf.sigmoid(tf.matmul(H3,W4)+b4)
cost = tf.reduce_mean((-1)*Y*tf.log(model) + (-1)*(1-Y)*tf.log(1-model))
train = tf.train.GradientDescentOptimizer(0.1).minimize(cost)